### ISSUE TITLE
AntiAD的规则数量不正常

### ISSUE THREAD

**Issue by MaoSuSu** [yaof-project/luci-app-ikoolproxy#98]
ikoolproxy中的antiad规则数量：
![image](https://user-images.githubusercontent.com/45323874/158413791-b257d164-6844-42e9-a527-c6cedf61abde.png)
antiad官网中的antiad规则数量：
![image](https://user-images.githubusercontent.com/45323874/158413929-d664666c-c789-4d46-be2e-3387e1cc4255.png)

今天无意中发现ikoolproxy中的antiad的规则数量几乎是原版antiad数量的两倍之多，不知是否是bug的问题呢？

**Comment by yaof-project** [comment]
转化的时候有http和https。
